name: Release

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
            submodules: recursive
            token: ${{ secrets.PACKAGE_TOKEN }}

      - name: Add GiHub Package Token
        run : echo "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGE_TOKEN }}" > ~/.npmrc

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.0

      - name: Configure Git User
        run: |
          git config --global user.email "erangerang15@gmail.com"
          git config --global user.name "Danji-ya"

      - name: Install dependencies
        run: yarn install

      - name: Build Packages
        run: yarn build

      - name: Publish
        run: |
          lerna publish from-package --yes