import type { NextPage } from 'next';
import Head from 'next/head';
import Navigation from '../components/Navigation';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>타이틀 지정</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <main>
        <p>hello world</p>
      </main>
    </div>
  )
}

export default Home
